export const CHANGE_PLAYER_LIST = 'player/CHANGE_PLAYER_LIST';
export const CHANGE_PLAYER_SONG_INDEX = 'player/CHANGE_PLAYER_SONG_INDEX';
export const CHANGE_CURRENT_SONG = 'player/CHANGE_CURRENT_SONG';

export const CHANGE_PLAYER_SEQUENCE = 'player/CHANGE_PLAYER_SEQUENCE';

export const CHANGE_CURRENT_LYRICS = 'player/CHANGE_CURRENT_LYRICS';
export const CHANGE_CURRENT_LYRIC_INDEX = 'player/CHANGE_CURRENT_LYRIC_INDEX';
