export const CHANGE_CATEGORY = 'songs/CHANGE_CATEGORY';
export const CHANGE_CURRENT_CATEGORY = 'songs/CHANGE_CURRENT_CATEGORY';
export const CHANGE_SONG_CATEGORY_LIST = 'songs/CHANGE_SONG_CATEGORY_LIST';

export const SONG_LIST_LIMIT = 35;
